### PR TITLE
Implemented chrome sync feature

### PR DESCRIPTION
**Pull request by wickles**
Simple change for syncing, re: issue https://github.com/Eloston/disable-html5-autoplay/issues/62

Just changed `storage.local` to `storage.sync`. For reference see [chrome.storage](https://developer.chrome.com/extensions/storage)

### CODE REVIEW

**Comment by Eloston** [comment]
Are you still able to save settings locally?

**Comment by wickles** [comment]
AFAIK it should work exactly the same as before, except that it will also sync between computers logged into your account if you have extension syncing enabled. Could add a switch if really desired (not necessary IMO).

**Comment by Eloston** [comment]
I just tried it out and it forgot all my local settings. I think it would be better for the users if it could migrate those settings automatically. 

Sync storage has a 5 kB max for the current implementation I believe, so should we just let the extension crash if it reaches the maximum size? On a side note, the `unlimitedStorage` permission should probably be removed since it is unnecessary now.

**Comment by wickles** [comment]
The sync storage size given by the docs as `QUOTA_BYTES` is 100 kB, so I wouldn't expect it to be an issue. Although it wouldn't hurt to add some error handling or just limit the amount a user can write in the mode rules list. 

You tried it as an upgrade with the same extension ID? I guess it might need some migration code then, not sure how best to handle that.

**Comment by Eloston** [comment]
> The sync storage size given by the docs as QUOTA_BYTES is 100 kB

That is correct, but Mode Rules are stored under the key `STORAGE_KEYS.MODE_RULES`, which is restricted by `QUOTA_BYTES_PER_ITEM` of 8 kB. The only way to use the remaining space is to add more keys.

> You tried it as an upgrade with the same extension ID?

I am pretty confident that my extension ID didn't change. I have the extension loaded from an unpacked directory, so I just replaced the files in there with your changes and reloaded the extension from `chrome://extensions`.

I don't find this behavior particularly surprising, considering they both have different storage limits and they are designed for different purposes. I could see use cases for using both storage types.

**Comment by wickles** [comment]
Ah, okay. I don't find the behavior particular surprising either but figured it was worth checking just in case. I was looking at other extensions' code recently, both storage types are definitely used concurrently. I will have a go at adding in the migration and get back to you.

**Comment by Eloston** [comment]
Alright, sounds good.

**Pull request closed without merging**
